package com.bfmanager.model.hibernate;
// Generated 18/10/2017 10:25:02 PM by Hibernate Tools 5.2.3.Final

/**
 * Answers generated by hbm2java
 */
public class Answers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idAnswer;
	private String answer;
	private long question;
	private Integer user;
	private Integer idSurvey;
	private Integer idGroup;

	public Answers() {
	}

	public Answers(long question) {
		this.question = question;
	}

	public Answers(String answer, long question, Integer user, Integer idSurvey, Integer idGroup) {
		this.answer = answer;
		this.question = question;
		this.user = user;
		this.idSurvey = idSurvey;
		this.idGroup = idGroup;
	}

	public Long getIdAnswer() {
		return this.idAnswer;
	}

	public void setIdAnswer(Long idAnswer) {
		this.idAnswer = idAnswer;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public long getQuestion() {
		return this.question;
	}

	public void setQuestion(long question) {
		this.question = question;
	}

	public Integer getUser() {
		return this.user;
	}

	public void setUser(Integer user) {
		this.user = user;
	}

	public Integer getIdSurvey() {
		return this.idSurvey;
	}

	public void setIdSurvey(Integer idSurvey) {
		this.idSurvey = idSurvey;
	}

	public Integer getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

}
