package com.bfmanager.model.hibernate;
// Generated 6/09/2017 11:14:34 PM by Hibernate Tools 5.2.3.Final

/**
 * DropDown generated by hbm2java
 */
public class DropDown implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long idDropDown;
	private String description;
	private Long question;

	public DropDown() {
	}

	public DropDown(String description, Long question) {
		this.description = description;
		this.question = question;
	}

	public Long getIdDropDown() {
		return this.idDropDown;
	}

	public void setIdDropDown(Long idDropDown) {
		this.idDropDown = idDropDown;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getQuestion() {
		return this.question;
	}

	public void setQuestion(Long question) {
		this.question = question;
	}

}
