package com.bfmanager.model.hibernate;
// Generated 2/08/2017 11:42:12 PM by Hibernate Tools 5.2.3.Final

/**
 * QuestionsType generated by hbm2java
 */
public class QuestionsType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idQuestionType;
	private String name;
	private String description;

	public QuestionsType() {
	}

	public QuestionsType(String name) {
		this.name = name;
	}

	public QuestionsType(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Integer getIdQuestionType() {
		return this.idQuestionType;
	}

	public void setIdQuestionType(Integer idQuestionType) {
		this.idQuestionType = idQuestionType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idQuestionType;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QuestionsType other = (QuestionsType) obj;
		if (idQuestionType != other.idQuestionType)
			return false;
		return true;
	}

}
