package com.bfmanager.model.hibernate;
// Generated 17/11/2017 04:16:03 PM by Hibernate Tools 5.2.3.Final

/**
 * Surveys generated by hbm2java
 */
public class Surveys implements java.io.Serializable {

private static final long serialVersionUID = 1L;
	
	private Integer idSurvey;
	private String title;
	private String description;
	private Users userOwner;
	private String instructions;
	private String shortDescription;
	private Boolean free;
	private byte[] banner;
	private String copyright;
	private SurveysType surveyType;
	private Boolean onlyOnce;
	private Boolean activated = false;

	public Surveys() {
	}

	public Surveys(String title, Users userOwner, String shortDescription, SurveysType surveyType) {
		this.title = title;
		this.userOwner = userOwner;
		this.shortDescription = shortDescription;
		this.surveyType = surveyType;
	}

	public Surveys(String title, String description, Users userOwner, String instructions, String shortDescription,
			Boolean free, byte[] banner, String copyright, SurveysType surveyType, Boolean onlyOnce, Boolean activated) {
		this.title = title;
		this.description = description;
		this.userOwner = userOwner;
		this.instructions = instructions;
		this.shortDescription = shortDescription;
		this.free = free;
		this.banner = banner;
		this.copyright = copyright;
		this.surveyType = surveyType;
		this.onlyOnce = onlyOnce;
		this.activated = activated;
	}

	public Integer getIdSurvey() {
		return this.idSurvey;
	}

	public void setIdSurvey(Integer idSurvey) {
		this.idSurvey = idSurvey;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Users getUserOwner() {
		return this.userOwner;
	}

	public void setUserOwner(Users userOwner) {
		this.userOwner = userOwner;
	}

	public String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(String instructions) {
		this.instructions = instructions;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public Boolean getFree() {
		return this.free;
	}

	public void setFree(Boolean free) {
		this.free = free;
	}

	public byte[] getBanner() {
		return this.banner;
	}

	public void setBanner(byte[] banner) {
		this.banner = banner;
	}

	public String getCopyright() {
		return this.copyright;
	}

	public void setCopyright(String copyright) {
		this.copyright = copyright;
	}

	public SurveysType getSurveyType() {
		return this.surveyType;
	}

	public void setSurveyType(SurveysType surveyType) {
		this.surveyType = surveyType;
	}

	public Boolean getOnlyOnce() {
		return this.onlyOnce;
	}

	public void setOnlyOnce(Boolean onlyOnce) {
		this.onlyOnce = onlyOnce;
	}

	public Boolean getActivated() {
		return this.activated;
	}

	public void setActivated(Boolean activated) {
		this.activated = activated;
	}

}
