package com.bfmanager.model.hibernate;
// Generated 15/10/2017 09:46:32 PM by Hibernate Tools 5.2.3.Final

/**
 * SurveysType generated by hbm2java
 */
public class SurveysType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSurveyType;
	private String type;
	private String description;

	public SurveysType() {
	}

	public SurveysType(String type, String description) {
		this.type = type;
		this.description = description;
	}

	public Integer getIdSurveyType() {
		return this.idSurveyType;
	}

	public void setIdSurveyType(Integer idSurveyType) {
		this.idSurveyType = idSurveyType;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idSurveyType;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SurveysType other = (SurveysType) obj;
		if (idSurveyType != other.idSurveyType)
			return false;
		return true;
	}

}
