package com.bfmanager.model.hibernate;
// Generated 18/10/2017 10:25:02 PM by Hibernate Tools 5.2.3.Final

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUserGroup;
	private Integer idGroup;
	private Integer idUser;

	public UserGroup() {
	}

	public UserGroup(Integer idGroup, Integer idUser) {
		this.idGroup = idGroup;
		this.idUser = idUser;
	}

	public Integer getIdUserGroup() {
		return this.idUserGroup;
	}

	public void setIdUserGroup(Integer idUserGroup) {
		this.idUserGroup = idUserGroup;
	}

	public Integer getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

}
